/* Activity Pulse — ambient, anonymous "someone is doing X" terminal ticker, crawling
   right-to-left under the About These Listings note (see #activity-rail in index.html/
   activity-pulse.css). Built from Live_Activity_Feed_Prompt.md (Step 1 only — the feed
   rail — per Sean's 2026-07-13 "no visible panel, just grey text" instruction; Step 2's
   bars panel and Step 3's live-dot indicator were intentionally NOT built). Visual design
   went through several passes the same night — grey upward drift, purple/blue color
   dissolve, size/opacity tuning — before landing on this horizontal terminal-style crawl
   per Sean's "go across... from side to side... nerdy terminal font and terminal green."

   Reuses the same Firebase project already wired up for Dance Whispers
   (window.WHISPER_FIREBASE_CONFIG, see index.html) under a new "activity" path, so
   there is no second Firebase project/account and no new config to manage.

   Privacy / trust model (see Live_Activity_Feed_Prompt.md for the full spec this
   follows):
   - No accounts, no identity, no IP/device info, ever.
   - Every signal is a short, enum-typed, templated fact (filter picked / view
     switched / event opened / correction form opened) — never visitor-typed text.
   - A visitor never sees a message generated by their own session (self-exclusion).
   - Event names are only ever resolved locally from dance_events.json by a trusted
     eventId lookup — a forged/malicious Firebase write can never inject arbitrary
     text into what's rendered, because unresolvable/unrecognized signals are
     dropped rather than displayed. Matches the "whitelist rendering" convention
     already used in app.js (comment: "rendering (whitelist only, textContent only)").
   - Nothing is fabricated: on a quiet night with no real visitors, the rail is
     simply empty. No fake activity is ever invented.

   Safe to ship even before the Firebase "activity" security rule is published —
   if the rule isn't there yet, writes silently fail and the rail just stays empty,
   same graceful-degradation pattern as Whispers/the viewer-count. */
(function () {
  "use strict";

  /* ---------- config ---------- */
  var MAX_VISIBLE = 2;                 // concurrent messages on screen at once — halved from 4
                                        // (2026-07-13, Sean: shrink the gap above the controls bar;
                                        // #activity-rail's CSS height was cut to match, see activity-pulse.css)
  var MAX_QUEUE = 8;                   // hard cap on the waiting queue — never let new activity get stuck
                                        // behind an unbounded backlog (see bug note below)
  var LIFETIME_MS = 15000;             // must match the CSS crawl duration (activity-ticker 15s in activity-pulse.css)
  var MIN_EMIT_INTERVAL_MS = 4000;     // per-session throttle across ALL signal types (batches rapid clicks)
  var EVENT_DEBOUNCE_MS = 3 * 60 * 1000;   // don't re-signal the same event from the same session for 3 min
  var MERGE_WINDOW_MS = 2500;          // buffer window for merging identical messages into "Two dancers are..."
  var PRUNE_AGE_MS = 10 * 60 * 1000;   // client-side trim: remove Firebase nodes older than this on load
  // Bug fix (2026-07-13): originally listened from (now - 5 minutes) so a newly-loaded page could show
  // a bit of recent history. Under real test volume this backfired badly — a burst of historical
  // child_added events on page load could fill the render queue faster than it drains (each visible
  // slot only frees every ~7.5s), pushing brand-new live signals up to 24s behind a stale backlog.
  // Only listening from "now" removes the backlog entirely; MAX_QUEUE above is a second line of
  // defense in case a genuine traffic burst ever produces more concurrent signals than can display at once.

  // Sean, 2026-07-13: "use less techy language... this is suppose to be a fun warm
  // environment." e.g. "a dancer is browsing in calendar view" -> "a dancer is looking
  // at the calendar." Plain, warm nouns instead of the app's own UI/filter jargon.
  var FRIENDLY_VIEW = {
    timeline: "the schedule", grid: "the grid", list: "the list", calendar: "the calendar", map: "the map"
  };
  var VALID_DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  var VALID_AREAS = ["Pensacola area", "Mobile area", "Elsewhere / unlisted"];
  var VALID_KINDS = ["Recurring", "One-time"];
  // Sean, 2026-07-13: "WSDC USA Dance arthur Murray and Fed Astarire are all treated as
  // styles. they can be used for this purpose too" — these four live outside the site's
  // normal style/category list (separate toggles, not dance_events.json style values), so
  // they need their own small whitelist alongside validCategories.
  var NATIONAL_TOGGLE_LABELS = ["WSDC", "USA Dance", "Arthur Murray", "Fred Astaire"];

  var sessionId = (function () {
    try {
      if (window.crypto && crypto.randomUUID) return crypto.randomUUID();
    } catch (e) { /* fall through */ }
    return "s" + Date.now().toString(36) + Math.random().toString(36).slice(2, 10);
  })();

  var lastEmitAt = 0;
  var eventCooldowns = Object.create(null);   // eventId -> last-signaled timestamp, this session only
  var eventNameByKey = null;                  // populated from dance_events.json — trusted lookup only
  var validCategories = null;                 // derived from dance_events.json's actual style values

  // Sean, 2026-07-13: "instead of using the word Mixed use mixed dances. same with
  // latin dances." Plain lowercase category name + "dances", unless the category
  // already reads naturally on its own (e.g. "Dance Fit" already says "dance").
  // The four national-source toggle names keep their original casing (proper nouns/
  // brand names, e.g. "WSDC" not "wsdc") rather than being lowercased like a style.
  function friendlyCategory(value) {
    if (NATIONAL_TOGGLE_LABELS.indexOf(value) !== -1) return value + " dances";
    var v = String(value).toLowerCase();
    if (v.indexOf("dance") !== -1) return v;
    return v + " dances";
  }

  function isValidCategory(value) {
    return typeof value === "string" &&
      ((validCategories && validCategories.has(value)) || NATIONAL_TOGGLE_LABELS.indexOf(value) !== -1);
  }

  /* ---------- message templates ----------
     Every template renders to a sentence starting "A dancer is " so the merge/pluralize
     step below can uniformly upgrade it to "Two dancers are ..." / "N dancers are ...".
     (Sean, 2026-07-13: "say 'A dancer' instead of 'someone'".) Wording kept plain and
     warm throughout — "use less techy language... this is suppose to be a fun warm
     environment" — no UI/filter jargon (view names, "listing," etc.). */
  function templateFor(sig) {
    switch (sig.type) {
      case "filter": {
        // Sean, 2026-07-13: "you can make the sentences more interesting if there is more
        // filters selected. the dance is interested in west coast swing dances on
        // thursday." — sig carries a full snapshot of every active filter dimension
        // (see filterSnapshotDetail() in app.js), and this composes ONE sentence from
        // whichever are actually set, rather than one generic line per click.
        var cat = isValidCategory(sig.cats) ? sig.cats : null;
        var day = (typeof sig.days === "string" && VALID_DAYS.indexOf(sig.days) !== -1) ? sig.days : null;
        var area = (typeof sig.areas === "string" && VALID_AREAS.indexOf(sig.areas) !== -1) ? sig.areas : null;
        var kind = (typeof sig.kinds === "string" && VALID_KINDS.indexOf(sig.kinds) !== -1) ? sig.kinds : null;
        if (!cat && !day && !area && !kind) return null;   // nothing recognizable — drop

        var subject = "A dancer" + (area ? " from " + area : "") + " is ";
        if (cat || kind) {
          var noun = cat ? friendlyCategory(cat) : (kind.toLowerCase() + " dances");
          if (cat && kind) noun = kind.toLowerCase() + " " + friendlyCategory(cat);
          var sentence = subject + "interested in " + noun;
          if (day) sentence += " on " + day;
          return sentence + ".";
        }
        if (day) return subject + "looking at " + day + "'s dances.";
        return "A dancer is looking at dances in the " + area + ".";   // area-only case (no redundant "from AREA... in the AREA")
      }
      case "view": {
        var label = FRIENDLY_VIEW[sig.view];
        if (!label) return null;
        return "A dancer is looking at " + label + ".";
      }
      case "event_viewed": {
        if (!eventNameByKey || !sig.eventId) return null;
        var name = eventNameByKey[sig.eventId];
        if (!name) return null;   // unresolvable eventId — drop, never render unverified text
        return "A dancer is checking out " + name + ".";
      }
      case "open_invite":
        return "A dancer is helping fix a dance listing.";
      default:
        return null;   // unknown/forged type — drop
    }
  }

  function pluralize(text, count) {
    if (count <= 1) return text;
    var subject = count === 2 ? "Two dancers" : count + " dancers";
    // Handles both "A dancer is ..." and "A dancer from X is ..." forms generically —
    // capture whatever sits between "A dancer" and the first " is ".
    return text.replace(/^A dancer(.*?) is /, function (_, middle) { return subject + middle + " are "; });
  }

  /* ---------- rail rendering ---------- */
  var railEl = null;
  var visibleCount = 0;
  var renderQueue = [];        // [{text, count}], waiting for a free slot
  var pendingBuffer = null;    // Map<text, count> — merge buffer, flushed on a timer
  var reducedMotion = false;
  // Sean, 2026-07-13 ("i mean instead of up the side"): messages now crawl horizontally,
  // so each concurrently-visible one gets its own starting ROW ("slot", reused terminology
  // from the earlier vertical design) instead of a vertical offset — up to MAX_VISIBLE
  // messages run on separate ticker lines so they don't overlap mid-crawl. Must roughly
  // match the row height baked into #activity-rail's CSS height (MAX_VISIBLE * ROW_HEIGHT_PX-ish).
  var ROW_HEIGHT_PX = 22;
  var slotFree = [];
  for (var __i = 0; __i < MAX_VISIBLE; __i++) slotFree.push(true);

  function claimSlot() {
    for (var i = 0; i < slotFree.length; i++) {
      if (slotFree[i]) { slotFree[i] = false; return i; }
    }
    return 0;   // shouldn't happen (tryShowNext already checks visibleCount < MAX_VISIBLE)
  }

  function tryShowNext() {
    if (visibleCount >= MAX_VISIBLE) return;
    var next = renderQueue.shift();
    if (!next) return;
    visibleCount++;
    var slot = claimSlot();
    var el = document.createElement("div");
    el.className = "activity-msg" + (reducedMotion ? " reduced" : "");
    el.textContent = pluralize(next.text, next.count);
    el.style.top = (slot * ROW_HEIGHT_PX) + "px";
    railEl.appendChild(el);
    setTimeout(function () {
      el.remove();
      slotFree[slot] = true;
      visibleCount--;
      tryShowNext();
    }, LIFETIME_MS);
    // A slot might free up again well before this message's own removal (if MAX_VISIBLE
    // was the limiter, not the queue being empty) — nothing else to do here, tryShowNext()
    // is re-invoked from the removal callback above, which is the only time a slot frees.
  }

  function enqueue(text, count) {
    if (renderQueue.length >= MAX_QUEUE) renderQueue.shift();   // drop oldest waiting item, never grow unbounded
    renderQueue.push({ text: text, count: count });
    tryShowNext();
  }

  function flushBuffer() {
    if (!pendingBuffer || pendingBuffer.size === 0) return;
    pendingBuffer.forEach(function (count, text) { enqueue(text, count); });
    pendingBuffer = null;
  }

  function bufferMessage(text) {
    if (!pendingBuffer) {
      pendingBuffer = new Map();
      setTimeout(flushBuffer, MERGE_WINDOW_MS);
    }
    pendingBuffer.set(text, (pendingBuffer.get(text) || 0) + 1);
  }

  /* ---------- incoming Firebase signal -> validated message ---------- */
  function handleIncoming(snap) {
    var s = snap.val();
    if (!s || typeof s !== "object") return;
    if (typeof s.sessionId !== "string" || typeof s.type !== "string") return;
    if (s.sessionId === sessionId) return;   // self-exclusion — never show a visitor their own activity
    var text = templateFor(s);
    if (!text) return;   // unrecognized type, or a value/eventId that doesn't resolve — drop silently
    bufferMessage(text);
  }

  /* ---------- outgoing: validate + throttle + write ---------- */
  function emit(detail) {
    var now = Date.now();
    if (now - lastEmitAt < MIN_EMIT_INTERVAL_MS) return;   // global per-session throttle (batches rapid clicks)

    if (detail.type === "event_viewed") {
      var last = eventCooldowns[detail.eventId] || 0;
      if (now - last < EVENT_DEBOUNCE_MS) return;          // don't spam the same event repeatedly
      eventCooldowns[detail.eventId] = now;
    }

    // Re-validate here too (not just at render time) so a bad payload is never written at all.
    var text = templateFor(detail);
    if (!text) return;

    lastEmitAt = now;
    var payload = { sessionId: sessionId, type: detail.type, ts: firebase.database.ServerValue.TIMESTAMP };
    if (detail.type === "filter") {
      // Full snapshot (see filterSnapshotDetail() in app.js) — only include fields that
      // are actually set, keeps written records small and matches what templateFor() reads.
      if (typeof detail.cats === "string") payload.cats = detail.cats;
      if (typeof detail.days === "string") payload.days = detail.days;
      if (typeof detail.areas === "string") payload.areas = detail.areas;
      if (typeof detail.kinds === "string") payload.kinds = detail.kinds;
    }
    if (detail.type === "view") { payload.view = detail.view; }
    if (detail.type === "event_viewed") { payload.eventId = detail.eventId; }
    try {
      window.__activityPulseRef.push(payload);
    } catch (e) { /* ambient nice-to-have only — never break the page over it */ }
  }

  /* ---------- boot ---------- */
  document.addEventListener("DOMContentLoaded", function () {
    railEl = document.getElementById("activity-rail");
    if (!railEl) return;   // markup not present, bail quietly

    try {
      reducedMotion = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    } catch (e) { /* default false */ }

    // Trusted event-name lookup, fetched independently of app.js (own copy, own scope —
    // never trusts anything read back from Firebase for event titles, only this).
    fetch("../dance_events.json")
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data) {
        var events = data && Array.isArray(data.events) ? data.events : [];
        var names = Object.create(null);
        var cats = new Set(["Other"]);
        events.forEach(function (ev) {
          if (ev && typeof ev.key === "string" && typeof ev.name === "string") names[ev.key] = ev.name.trim();
          if (ev && typeof ev.style === "string" && ev.style.trim()) cats.add(ev.style.trim());
        });
        eventNameByKey = names;
        validCategories = cats;
      })
      .catch(function () { eventNameByKey = {}; validCategories = new Set(["Other"]); });

    var cfg = window.WHISPER_FIREBASE_CONFIG;
    if (!cfg || !cfg.apiKey || typeof firebase === "undefined") return;   // stays quietly empty, same as Whispers

    if (!firebase.apps || !firebase.apps.length) firebase.initializeApp(cfg);
    var db = firebase.database();
    var activityRef = db.ref("activity");
    window.__activityPulseRef = activityRef;

    // One-time client-side prune of stale nodes (Firebase has no native TTL) — non-critical,
    // wrapped defensively; if the security rule doesn't allow removal yet this just no-ops.
    try {
      activityRef.orderByChild("ts").endAt(Date.now() - PRUNE_AGE_MS).once("value", function (snap) {
        snap.forEach(function (child) { child.ref.remove().catch(function () {}); });
      });
    } catch (e) { /* non-critical */ }

    // Only truly new signals from this moment forward — see the bug note above for why this
    // isn't `startAt(Date.now() - 5min)` anymore.
    activityRef.orderByChild("ts").startAt(Date.now()).on("child_added", handleIncoming);

    // Listen for the semantic signals app.js dispatches at the moment of an actual
    // filter click / view switch / event open / correction-form open — app.js already
    // has the trusted, non-user-editable value in hand at each of those points.
    window.addEventListener("activity-signal", function (e) {
      if (e && e.detail) emit(e.detail);
    });
  });
})();
